### ISSUE TITLE
Object #<Filepicker> has no method 'getFileSelectDialog'

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [AppWerft/Ti.FilePicker#3]
When i try to run the file picker it return this issue
Object #<Filepicker> has no method 'getFileSelectDialog'

**Comment by AppWerft** [comment]
Let us screen share

**Comment by AppWerft** [comment]
You are right: this are the methods:
getFile()

**Comment by MahmoudElmoghazy** [comment]
Thanks put this option doesn't make any thing it doesn't work

**Comment by MahmoudElmoghazy** [comment]
I finally found the solution 

```
var intent = Ti.Android.createIntent({
        action: Ti.Android.ACTION_GET_CONTENT,
        type: "application/pdf"
      });

      var x = Ti.Android.createIntentChooser(intent, "Select");
      $.win.getActivity().startActivityForResult(x, function(e) {

        try {
          var file = Ti.Filesystem.getFile(e.intent.data);
          Ti.API.info("file is: " + file);
        } catch (error) {
          console.error("This is error : " + error);
        }
      });
```

**Comment by balasug** [comment]
> I finally found the solution
> 
> ```
> var intent = Ti.Android.createIntent({
>         action: Ti.Android.ACTION_GET_CONTENT,
>         type: "application/pdf"
>       });
> 
>       var x = Ti.Android.createIntentChooser(intent, "Select");
>       $.win.getActivity().startActivityForResult(x, function(e) {
> 
>         try {
>           var file = Ti.Filesystem.getFile(e.intent.data);
>           Ti.API.info("file is: " + file);
>         } catch (error) {
>           console.error("This is error : " + error);
>         }
>       });
> ```

Does it work?
